### PR TITLE
debian: Script to create debian package

### PR DESCRIPTION
**Pull request by Rishabh4275**
Skeleton Script to create Debian package under DebianBuild Folder that is at the level of the repository
Changes to the debian folder created need to be added to the script

Signed-off-by: Rishabh Chawla <rishabhchawla1995@gmail.com>

### CODE REVIEW

**Comment by Rishabh4275** [comment]
Updating the [issue](https://github.com/westerndigitalcorporation/libzbd/issues/4) with the changes that would be needed.

**Comment by damien-lemoal** [comment]
Working on this right now. Instead of a shell script, I am preparing a "make deb" directive to build the debian packages from Makefile.am. Will be posting this in the staging branch very soon for you to test.

**Comment by Rishabh4275** [comment]
Thank you.

**Comment by damien-lemoal** [comment]
Resolved. Different patches added to staging branch.

**Pull request closed without merging**
