### PR TITLE
Sync debian packaging files

### PR DESCRIPTION
**Pull request by sudipm-mukherjee**
Sync the Debian packaging files in debian/* as of Debian package version 2.0.2-2.
Link: https://tracker.debian.org/pkg/libzbd
Source: https://salsa.debian.org/sudip/libzbd

### CODE REVIEW

**Comment by damien-lemoal** [comment]
This looks OK to me. Just one remark: The Fedora RPMs are split into libzbd, libzbd-devel, libzbd-cli-tools and libzbd-gtk-tools. Would it make sense to follow the same split for debian packages ?
Not being very familiar with Debian, I am not sure what the convention is.

**Comment by sudipm-mukherjee** [comment]
Hi @damien-lemoal,
There is no such convention. Even if it is split in two different packages, they will still be part of "utils" section. I am not really seeing any advantage in splitting them now. But otoh, if the packages are split now it might cause problem for users who will upgrade to Debian 12 from Debian 11, as libzbd in the current packages is already there in Bullseye release.

**Comment by damien-lemoal** [comment]
> Hi @damien-lemoal, There is no such convention. Even if it is split in two different packages, they will still be part of "utils" section. I am not really seeing any advantage in splitting them now. But otoh, if the packages are split now it might cause problem for users who will upgrade to Debian 12 from Debian 11, as libzbd in the current packages is already there in Bullseye release.

Understood.

**Comment by damien-lemoal** [comment]
Applied. Thanks !

**Pull request merged**
